INSERT INTO "Promotion" (
  "id",
  "code",
  "title",
  "discountType",
  "discountValue",
  "minSpend",
  "usageLimit",
  "placement",
  "bannerKicker",
  "bannerTitle",
  "bannerBody",
  "bannerCta",
  "bannerBadge",
  "destinationCategory",
  "location",
  "displayOrder",
  "active",
  "startDate",
  "createdAt"
) VALUES
  (
    'needly-home-ad-open-market',
    'HOME-OPEN-MARKET',
    'Open Market',
    'PERCENT',
    0,
    0,
    100,
    'HOMEPAGE_CAROUSEL',
    'Open Market',
    'Fresh from Abeokuta',
    'Shop quality products from local sellers.',
    'Shop Open Market',
    'Supporting Local Abeokuta',
    'Local Market',
    'Abeokuta',
    1,
    true,
    NOW(),
    NOW()
  ),
  (
    'needly-home-ad-food',
    'HOME-FOOD',
    'Food & Restaurants',
    'PERCENT',
    0,
    0,
    100,
    'HOMEPAGE_CAROUSEL',
    'Food & Restaurants',
    'Your favourite meals',
    'Order hot food from trusted Abeokuta vendors.',
    'Order Food',
    'Fast local delivery',
    'Restaurant',
    'Abeokuta',
    2,
    true,
    NOW(),
    NOW()
  ),
  (
    'needly-home-ad-auto',
    'HOME-AUTO',
    'Auto Services',
    'PERCENT',
    0,
    0,
    100,
    'HOMEPAGE_CAROUSEL',
    'Auto Services',
    'Fix, wash, move',
    'Mechanics, car wash and driver services nearby.',
    'Book Auto',
    'Verified providers',
    'Auto',
    'Abeokuta',
    3,
    true,
    NOW(),
    NOW()
  ),
  (
    'needly-home-ad-home-services',
    'HOME-SERVICES',
    'Home Services',
    'PERCENT',
    0,
    0,
    100,
    'HOMEPAGE_CAROUSEL',
    'Home Services',
    'Help at home',
    'Cleaners, laundry and repairs when you need them.',
    'Book Service',
    'Home support',
    'Home Services',
    'Abeokuta',
    4,
    true,
    NOW(),
    NOW()
  ),
  (
    'needly-home-ad-special-offers',
    'HOME-SPECIAL-OFFERS',
    'Special Offers',
    'PERCENT',
    0,
    0,
    100,
    'HOMEPAGE_CAROUSEL',
    'Special Offers',
    'Deals around you',
    'Save on selected essentials and local favourites.',
    'Shop Deals',
    'Limited time',
    'Supermarket',
    'Abeokuta',
    5,
    true,
    NOW(),
    NOW()
  )
ON CONFLICT ("code") DO NOTHING;
