services:
  - type: web
    name: needly-backend
    runtime: node
    plan: free
    region: oregon
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: FLUTTERWAVE_CLIENT_ID
        sync: false
      - key: FLUTTERWAVE_CLIENT_SECRET
        sync: false
      - key: FLUTTERWAVE_PUBLIC_KEY
        sync: false
      - key: FLUTTERWAVE_SECRET_KEY
        sync: false
      - key: FLUTTERWAVE_ENCRYPTION_KEY
        sync: false
      - key: FLUTTERWAVE_WEBHOOK_SECRET_HASH
        sync: false
      - key: PORT
        value: "4000"
      - key: APP_BASE_URL
        value: https://needly-backend-7tap.onrender.com
      - key: FRONTEND_BASE_URL
        value: https://needly-frontend-seven.vercel.app
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_SECURE
        value: "false"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: MAIL_FROM
        value: Needly <hello@needly.market>
      - key: ALLOWED_AREAS
        value: Abeokuta,Adigbe,Panseke,Oke-Ilewo,Lafenwa,Kuto,Omida
      - key: AUTO_SEED_DEMO
        value: "false"
      - key: RIDER_PAYOUT_PER_DELIVERY
        value: "600"
      - key: ALLOWED_ORIGINS
        value: https://needly-frontend-seven.vercel.app,https://needly-frontend-git-main-autokeys.vercel.app
