ALTER TABLE "Payment"
ADD COLUMN "vendorAmount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "platformFeeAmount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "platformFeePercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "deliveryFeeAmount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "deliveryDistanceKm" DOUBLE PRECISION,
ADD COLUMN "vendorReceived" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "vendorReceivedAt" TIMESTAMP(3),
ADD COLUMN "vendorReceivedById" TEXT;
