ALTER TABLE "Vendor" ADD COLUMN "address" TEXT;
ALTER TABLE "Vendor" ADD COLUMN "latitude" DOUBLE PRECISION;
ALTER TABLE "Vendor" ADD COLUMN "longitude" DOUBLE PRECISION;

ALTER TABLE "Rider" ADD COLUMN "latitude" DOUBLE PRECISION;
ALTER TABLE "Rider" ADD COLUMN "longitude" DOUBLE PRECISION;

ALTER TABLE "Order" ADD COLUMN "deliveryLatitude" DOUBLE PRECISION;
ALTER TABLE "Order" ADD COLUMN "deliveryLongitude" DOUBLE PRECISION;
