INSERT INTO "Location" ("id", "state", "name", "type", "active", "deliveryFee", "maxDistance", "createdAt")
VALUES
  ('loc-ng-abia-umuahia', 'Abia', 'Umuahia', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-adamawa-yola', 'Adamawa', 'Yola', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-akwa-ibom-uyo', 'Akwa Ibom', 'Uyo', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-anambra-awka', 'Anambra', 'Awka', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-bauchi-bauchi', 'Bauchi', 'Bauchi', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-bayelsa-yenagoa', 'Bayelsa', 'Yenagoa', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-benue-makurdi', 'Benue', 'Makurdi', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-borno-maiduguri', 'Borno', 'Maiduguri', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-cross-river-calabar', 'Cross River', 'Calabar', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-delta-asaba', 'Delta', 'Asaba', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-ebonyi-abakaliki', 'Ebonyi', 'Abakaliki', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-edo-benin-city', 'Edo', 'Benin City', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-ekiti-ado-ekiti', 'Ekiti', 'Ado-Ekiti', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-enugu-enugu', 'Enugu', 'Enugu', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-fct-abuja', 'FCT', 'Abuja', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-gombe-gombe', 'Gombe', 'Gombe', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-imo-owerri', 'Imo', 'Owerri', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-jigawa-dutse', 'Jigawa', 'Dutse', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-kaduna-kaduna', 'Kaduna', 'Kaduna', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-kano-kano', 'Kano', 'Kano', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-katsina-katsina', 'Katsina', 'Katsina', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-kebbi-birnin-kebbi', 'Kebbi', 'Birnin Kebbi', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-kogi-lokoja', 'Kogi', 'Lokoja', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-kwara-ilorin', 'Kwara', 'Ilorin', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-lagos-lagos', 'Lagos', 'Lagos', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-nasarawa-lafia', 'Nasarawa', 'Lafia', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-niger-minna', 'Niger', 'Minna', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-ogun-abeokuta', 'Ogun', 'Abeokuta', 'CITY', true, 500, 35, NOW()),
  ('loc-ng-ondo-akure', 'Ondo', 'Akure', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-osun-osogbo', 'Osun', 'Osogbo', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-oyo-ibadan', 'Oyo', 'Ibadan', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-plateau-jos', 'Plateau', 'Jos', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-rivers-port-harcourt', 'Rivers', 'Port Harcourt', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-sokoto-sokoto', 'Sokoto', 'Sokoto', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-taraba-jalingo', 'Taraba', 'Jalingo', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-yobe-damaturu', 'Yobe', 'Damaturu', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-zamfara-gusau', 'Zamfara', 'Gusau', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-anambra-onitsha', 'Anambra', 'Onitsha', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-anambra-nnewi', 'Anambra', 'Nnewi', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-delta-warri', 'Delta', 'Warri', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-edo-auchi', 'Edo', 'Auchi', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-fct-gwarinpa', 'FCT', 'Gwarinpa', 'AREA', true, 700, 25, NOW()),
  ('loc-ng-fct-garki', 'FCT', 'Garki', 'AREA', true, 700, 25, NOW()),
  ('loc-ng-fct-wuse', 'FCT', 'Wuse', 'AREA', true, 700, 25, NOW()),
  ('loc-ng-fct-kubwa', 'FCT', 'Kubwa', 'AREA', true, 700, 25, NOW()),
  ('loc-ng-kaduna-zaria', 'Kaduna', 'Zaria', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-kwara-offa', 'Kwara', 'Offa', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-lagos-ikeja', 'Lagos', 'Ikeja', 'AREA', true, 700, 25, NOW()),
  ('loc-ng-lagos-lekki', 'Lagos', 'Lekki', 'AREA', true, 700, 25, NOW()),
  ('loc-ng-lagos-victoria-island', 'Lagos', 'Victoria Island', 'AREA', true, 700, 25, NOW()),
  ('loc-ng-lagos-ajah', 'Lagos', 'Ajah', 'AREA', true, 700, 25, NOW()),
  ('loc-ng-lagos-yaba', 'Lagos', 'Yaba', 'AREA', true, 700, 25, NOW()),
  ('loc-ng-lagos-surulere', 'Lagos', 'Surulere', 'AREA', true, 700, 25, NOW()),
  ('loc-ng-lagos-ikorodu', 'Lagos', 'Ikorodu', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-ogun-ijebu-ode', 'Ogun', 'Ijebu Ode', 'CITY', true, 500, 35, NOW()),
  ('loc-ng-ogun-sagamu', 'Ogun', 'Sagamu', 'CITY', true, 500, 35, NOW()),
  ('loc-ng-ogun-ota', 'Ogun', 'Ota', 'CITY', true, 500, 35, NOW()),
  ('loc-ng-ogun-ilaro', 'Ogun', 'Ilaro', 'CITY', true, 500, 35, NOW()),
  ('loc-ng-ogun-mowe', 'Ogun', 'Mowe', 'CITY', true, 500, 35, NOW()),
  ('loc-ng-ondo-ondo-city', 'Ondo', 'Ondo City', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-ondo-owo', 'Ondo', 'Owo', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-osun-ile-ife', 'Osun', 'Ile-Ife', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-osun-ilesa', 'Osun', 'Ilesa', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-oyo-ogbomoso', 'Oyo', 'Ogbomoso', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-oyo-oyo', 'Oyo', 'Oyo', 'CITY', true, 700, 35, NOW()),
  ('loc-ng-rivers-bonny', 'Rivers', 'Bonny', 'CITY', true, 700, 35, NOW())
ON CONFLICT ("id") DO UPDATE
SET "state" = EXCLUDED."state",
    "name" = EXCLUDED."name",
    "type" = EXCLUDED."type",
    "active" = true,
    "deliveryFee" = EXCLUDED."deliveryFee",
    "maxDistance" = EXCLUDED."maxDistance";

UPDATE "Category"
SET "location" = NULL
WHERE "location" = 'Abeokuta';
