ALTER TABLE "Vendor" ADD COLUMN IF NOT EXISTS "bankName" TEXT;
ALTER TABLE "Vendor" ADD COLUMN IF NOT EXISTS "bankAccountNumber" TEXT;
ALTER TABLE "Vendor" ADD COLUMN IF NOT EXISTS "bankAccountName" TEXT;
ALTER TABLE "Vendor" ADD COLUMN IF NOT EXISTS "bankAccountLocked" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Vendor" ADD COLUMN IF NOT EXISTS "bankAccountLockedAt" TIMESTAMP(3);
